services:
  app:
    container_name: blog-app
    build:
      context: .
    working_dir: /app         # ✅ chuyển dòng này ra ngoài `build`
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGODB_URI: mongodb://mongo:27017/blog
      RABBITMQ_URI: amqp://rabbitmq
    command: sh -c "yarn install && yarn start"

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
