version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn start"
    ports:
      - "3001:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/blog 

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
