version: '3.8'

services:
  app:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGODB_URI: mongodb://mongo:27017/blog
      RABBITMQ_URI: amqp://rabbitmq

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
