// src/cron/dailyReport.js
const fs = require('fs');
const path = require('path');

async function generateDailyReport(job) {
  const now = new Date();

  const folderPath = path.join(__dirname, '../../reports', now.toISOString().split('T')[0]);
  fs.mkdirSync(folderPath, { recursive: true });

  const data = {
    timestamp: now.toISOString(),
    status: 'done',
    source: job.source || 'unknown',
    message: '📄 Daily report generated by RabbitMQ consumer'
  };

  const filePath = path.join(folderPath, `report-${Date.now()}.json`);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));

  console.log("✅ Daily report created:", filePath); // Bạn cần dòng này để biết chạy thành công
}

module.exports = generateDailyReport;
